import createAsyncStrapFactory from '../../helpers/async-strap-factory'

export default {
  // Internal straps
  'strap-empty': createAsyncStrapFactory(() => import(/* webpackChunkName: "strap-empty" */ './StrapEmpty')),
  'strap-error': createAsyncStrapFactory(() => import(/* webpackChunkName: "strap-error" */ './StrapError')),

  // Straps
  'strap-about-image-aside': createAsyncStrapFactory(() => import(/* webpackChunkName: "strap-about-image-aside" */ './StrapAboutImageAside')),
  'strap-about-simple': createAsyncStrapFactory(() => import(/* webpackChunkName: "strap-about-simple" */ './StrapAboutSimple')),
  'strap-advanced-search': createAsyncStrapFactory(() => import(/* webpackChunkName: "strap-advanced-search" */ './StrapAdvancedSearch')),
  'strap-agent-daily-featured': createAsyncStrapFactory(() => import(/* webpackChunkName: "strap-agent-daily-featured" */ './StrapAgentDailyFeatured')),
  'strap-agent-rotator': createAsyncStrapFactory(() => import(/* webpackChunkName: "strap-agent-rotator" */ './StrapAgentRotator')),
  'strap-agent-search': createAsyncStrapFactory(() => import(/* webpackChunkName: "strap-agent-search" */ './StrapAgentSearch')),
  'strap-agent-search-display': createAsyncStrapFactory(() => import(/* webpackChunkName: "strap-agent-search-display" */ './StrapAgentSearchDisplay')),
  'strap-basic-search': createAsyncStrapFactory(() => import(/* webpackChunkName: "strap-basic-search" */ './StrapBasicSearch')),
  'strap-basic-search-with-buttons': createAsyncStrapFactory(() => import(/* webpackChunkName: "strap-basic-search-with-buttons" */ './StrapBasicSearchWithButtons')),
  'strap-blog-feed': createAsyncStrapFactory(() => import(/* webpackChunkName: "strap-blog-feed" */ './StrapBlogFeed')),
  'strap-blog-post': createAsyncStrapFactory(() => import(/* webpackChunkName: "strap-blog-post" */ './StrapBlogPost')),
  'strap-big-icons': createAsyncStrapFactory(() => import(/* webpackChunkName: "strap-big-icons" */ './StrapBigIcons')),
  'strap-buyers-sellers-resources': createAsyncStrapFactory(() => import(/* webpackChunkName: "strap-buyers-sellers-resources" */ './StrapBuyersSellersResources')),
  'strap-columned-links': createAsyncStrapFactory(() => import(/* webpackChunkName: "strap-columned-links" */ './StrapColumnedLinks')),
  'strap-columned-tiles': createAsyncStrapFactory(() => import(/* webpackChunkName: "strap-columned-tiles" */ './StrapColumnedTiles')),
  'strap-compare-block': createAsyncStrapFactory(() => import(/* webpackChunkName: "strap-compare-block" */ './StrapCompareBlock')),
  'strap-featured-agent': createAsyncStrapFactory(() => import(/* webpackChunkName: "strap-featured-agent" */ './StrapFeaturedAgent')),
  'strap-featured-listing': createAsyncStrapFactory(() => import(/* webpackChunkName: "strap-featured-listing" */ './StrapFeaturedListing')),
  'strap-form': createAsyncStrapFactory(() => import(/* webpackChunkName: "strap-form" */ './StrapForm')),
  'strap-form-aside': createAsyncStrapFactory(() => import(/* webpackChunkName: "strap-form-aside" */ './StrapFormAside')),
  'strap-gallery': createAsyncStrapFactory(() => import(/* webpackChunkName: "strap-gallery" */ './StrapGallery')),
  'strap-html': createAsyncStrapFactory(() => import(/* webpackChunkName: "strap-html" */ './StrapHtml')),
  'strap-html-columns': createAsyncStrapFactory(() => import(/* webpackChunkName: "strap-html-columns" */ './StrapHtmlColumns')),
  'strap-html-contained': createAsyncStrapFactory(() => import(/* webpackChunkName: "strap-html-contained" */ './StrapHtmlContained')),
  'strap-html-slider': createAsyncStrapFactory(() => import(/* webpackChunkName: "strap-html-slider" */ './StrapHtmlSlider')),
  'strap-image-strip': createAsyncStrapFactory(() => import(/* webpackChunkName: "strap-image-strip" */ './StrapImageStrip')),
  'strap-image': createAsyncStrapFactory(() => import(/* webpackChunkName: "strap-image" */ './StrapImage')),
  'strap-large-about-image-aside': createAsyncStrapFactory(() => import(/* webpackChunkName: "strap-large-about-image-aside" */ './StrapLargeAboutImageAside')),
  'strap-large-listings-feed': createAsyncStrapFactory(() => import(/* webpackChunkName: "strap-large-listings-feed" */ './StrapLargeListingsFeed')),
  'strap-large-open-house-feed': createAsyncStrapFactory(() => import(/* webpackChunkName: "strap-large-open-house-feed" */ './StrapLargeOpenHouseFeed')),
  'strap-latest-listings': createAsyncStrapFactory(() => import(/* webpackChunkName: "strap-latest-listings" */ './StrapLatestListings')),
  'strap-latest-listings-across': createAsyncStrapFactory(() => import(/* webpackChunkName: "strap-latest-listings-across" */ './StrapLatestListingsAcross')),
  'strap-latest-news': createAsyncStrapFactory(() => import(/* webpackChunkName: "strap-latest-news" */ './StrapLatestNews')),
  'strap-latest-social': createAsyncStrapFactory(() => import(/* webpackChunkName: "strap-latest-social" */ './StrapLatestSocial')),
  'strap-listing-details': createAsyncStrapFactory(() => import(/* webpackChunkName: "strap-listing-details" */ './StrapListingDetails')),
  'strap-new-listing-details': createAsyncStrapFactory(() => import(/* webpackChunkName: "strap-new-listing-details" */ './StrapNewListingDetails')),
  'strap-sold-details': createAsyncStrapFactory(() => import(/* webpackChunkName: "strap-sold-details" */ './StrapSoldDetails')),
  'strap-listing-search': createAsyncStrapFactory(() => import(/* webpackChunkName: "strap-listing-search" */ './StrapListingSearch')),
  'strap-map-listing-search': createAsyncStrapFactory(() => import(/* webpackChunkName: "strap-map-listing-search" */ './StrapMapListingSearch')),
  'strap-listings-feed': createAsyncStrapFactory(() => import(/* webpackChunkName: "strap-listings-feed" */ './StrapListingsFeed')),
  'strap-sold-listings-feed': createAsyncStrapFactory(() => import(/* webpackChunkName: "strap-listings-feed" */ './StrapSoldListingsFeed')),
  'strap-listings-sold': createAsyncStrapFactory(() => import(/* webpackChunkName: "strap-listings-sold" */ './StrapListingsSold')),
  'strap-market-stats': createAsyncStrapFactory(() => import(/* webpackChunkName: "strap-market-stats" */ './StrapMarketStats')),
  'strap-market-stats-slim': createAsyncStrapFactory(() => import(/* webpackChunkName: "strap-market-stats-slim" */ './StrapMarketStatsSlim')),
  'strap-mosaic': createAsyncStrapFactory(() => import(/* webpackChunkName: "strap-mosaic" */ './StrapMosaic')),
  'strap-multi-agent-rotator': createAsyncStrapFactory(() => import(/* webpackChunkName: "strap-multi-agent-rotator" */ './StrapMultiAgentRotator')),
  'strap-quote-slider': createAsyncStrapFactory(() => import(/* webpackChunkName: "strap-quote-slider" */ './StrapQuoteSlider')),
  'strap-quote': createAsyncStrapFactory(() => import(/* webpackChunkName: "strap-quote" */ './StrapQuote')),
  'strap-spotlight': createAsyncStrapFactory(() => import(/* webpackChunkName: "strap-spotlight" */ './StrapSpotlight')),
  'strap-team-roster-strip': createAsyncStrapFactory(() => import(/* webpackChunkName: "strap-team-roster-strip" */ './StrapTeamRosterStrip')),
  'strap-testimonial': createAsyncStrapFactory(() => import(/* webpackChunkName: "strap-testimonial" */ './StrapTestimonial')),
  'strap-text': createAsyncStrapFactory(() => import(/* webpackChunkName: "strap-text" */ './StrapText')),
  'strap-text-with-columned-links': createAsyncStrapFactory(() => import(/* webpackChunkName: "strap-text-with-columned-links" */ './StrapTextWithColumnedLinks')),
  'strap-text-with-image': createAsyncStrapFactory(() => import(/* webpackChunkName: "strap-text-with-image" */ './StrapTextWithImage')),
  'strap-video': createAsyncStrapFactory(() => import(/* webpackChunkName: "strap-video" */ './StrapVideo')),
  'strap-video-aside': createAsyncStrapFactory(() => import(/* webpackChunkName: "strap-video-aside" */ './StrapVideoAside')),
  'strap-video-columns': createAsyncStrapFactory(() => import(/* webpackChunkName: "strap-video-columns" */ './StrapVideoColumns')),
  'strap-video-with-text': createAsyncStrapFactory(() => import(/* webpackChunkName: "strap-video-with-text" */ './StrapVideoWithText'))
}
